#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $STUDENT_USERNAME WITH PASSWORD '$STUDENT_PASSWORD';
    CREATE DATABASE $STUDENT_LOCAL_DATABASE;
    GRANT ALL privileges ON DATABASE $STUDENT_LOCAL_DATABASE to $STUDENT_USERNAME;
    CREATE DATABASE $STUDENT_TEST_DATABASE;
    GRANT ALL privileges ON DATABASE $STUDENT_TEST_DATABASE to $STUDENT_USERNAME;
EOSQL